### ISSUE TITLE
random error when launching btd6

### ISSUE THREAD

**Issue by tkosah** [hemisemidemipresent/btd6-modding-tutorial#26]
![image](https://user-images.githubusercontent.com/124846768/217686198-8ffba63b-b2f0-4e57-b14f-ca37fda30813.png)
I don't know what's wrong exactly I followed all the steps on melon loader

**Comment by tkosah** [comment]
I replaced the files in my btd6 directory and now I got this error 
![image](https://user-images.githubusercontent.com/124846768/217687006-04d48d48-9087-4202-88ad-f4832023cb74.png)

**Comment by Timotheeee** [comment]
I've added this issue to the troubleshooting section
