### ISSUE TITLE
Melon Loader throwing an exception. Followed the steps exactly as shown on readme.md

### ISSUE THREAD

**Issue by Arpitpatel1771** [hemisemidemipresent/btd6-modding-tutorial#27]
This is the error trace
![image](https://user-images.githubusercontent.com/28670605/219409192-d8de4b24-cc14-426d-a0ee-9ca380837a24.png)
the only mod in the mod folder is mod helper which was installed as described by you.

Please help me figure out a solution for this issue. Thanks!

**Comment by Timotheeee** [comment]
added that to the troubleshooting section
